### PR TITLE
fix: Make neqo pass `amplificationlimit` QNS test

### LINKED ISSUE #1183: Disable PTO at server if path is not validated
We currently send probes on PTO always.  However a server is not allowed to when the active path hasn't been validated.  This is preventing us from passing amplification limit tests.

This is not particularly urgent as we don't ship a server currently.  But it is also a relatively small amount of work.  The only challenge might be getting the path validation state to the right place(s).  We have tests for the amplification limit, but these are flawed (they pass, they should not), so the biggest part of this work is in tweaking those tests.

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #1183

### CODE REVIEW

File: neqo-transport/src/connection/mod.rs [hunk 1]
```diff
@@ -1462,6 +1462,10 @@ impl Connection {
             // We only allow one path during setup, so apply handshake
             // path validation to this path.
             path.borrow_mut().set_valid(now);
+        } else if self.role == Role::Client && packet.packet_type() == PacketType::Initial {
+            // If we are a client and we receive an Initial packet, we can
+            // assume that the server has validated the path.
+            path.borrow_mut().set_valid(now);
```
Comment (martinthomson) [inline neqo-transport/src/connection/mod.rs:1468]: This is obviously true, but what circumstances lead to a client not having a valid path at this point?  We are calling `setup_handshake_path` at the client as soon as the path is created, so this would have to involve some sort of migration during the handshake, right?

Put differently, does the test fail if you remove this block of code?

File: neqo-transport/src/connection/tests/handshake.rs [hunk 2]
```diff
@@ -768,16 +768,11 @@ fn anti_amplification() {
...
-    let s_pacing = server.process_output(now).callback();
-    assert_ne!(s_pacing, Duration::new(0, 0));
-    now += s_pacing;
-
     let s_init3 = server.process_output(now).dgram().unwrap();
     assert_eq!(s_init3.len(), PATH_MTU_V6);
     let cb = server.process_output(now).callback();
-    assert_ne!(cb, Duration::new(0, 0));
+    // We are blocked by the amplification limit now.
+    assert_eq!(cb, Duration::from_millis(300));
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/handshake.rs:775]:
```suggestion
    assert_eq!(cb, DEFAULT_RTT * 3);
```

You want this to be relative to the RTT, I think.

File: neqo-transport/src/recovery.rs [hunk 3]
```diff
@@ -968,7 +968,9 @@ impl LossRecovery {
         }
         self.stats.borrow_mut().lost += lost_packets.len();
 
-        self.maybe_fire_pto(primary_path.borrow().rtt(), now, &mut lost_packets);
+        if primary_path.borrow().is_valid() {
+            self.maybe_fire_pto(primary_path.borrow().rtt(), now, &mut lost_packets);
+        }
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs:973]: Perhaps the right thing to do is pass the `PathRef` into `maybe_fire_pto`, so that the "maybe" can do the extra work (and so you can borrow just once).

File: qns/interop.sh [hunk 4]
```diff
@@ -26,7 +26,7 @@ server)
     -name "$CERT" -passout pass: -out "$P12CERT"
   pk12util -d "sql:$DB" -i "$P12CERT" -W ''
   certutil -L -d "sql:$DB" -n "$CERT"
-  RUST_LOG=info RUST_BACKTRACE=1 neqo-server --cc cubic --qns-test "$TESTCASE" \
+  RUST_LOG=debug RUST_BACKTRACE=1 neqo-server --cc cubic --qns-test "$TESTCASE" \
```
Comment (martinthomson) [inline qns/interop.sh:29]: :+1: 

I've been meaning to do this for testing server interop stuff.

**Comment by larseggert** [comment]
One test not passing, see https://github.com/mozilla/neqo/issues/1490#issuecomment-2095562404

**Comment by larseggert** [comment]
@martinthomson @KershawChang if any of you understands the timer code, I'd appreciate some help here. The `idle_timeout_crazy_rtt` persistently crashes with `assertion failed: earliest > now`, which seems to be a long-standing issue.

It's straightforward to reproduce:
```
# RUST_LOG=trace cargo nextest run --no-capture idle_timeout_crazy_rtt
...
0s 35ms DEBUG [idle_timeout_crazy_rtt] processing Server c11688b68f20d6a8b4f512e565e90a
0s 35ms TRACE [Server c11688b68f20d6a8b4f512e565e90a] process_output Handshaking Instant { tv_sec: 5648807, tv_nsec: 122490916 }
0s 35ms TRACE IdleTimeout::expiry@Instant { tv_sec: 5648807, tv_nsec: 122490916 } pto=325ms, ka=false => Instant { tv_sec: 610448805, tv_nsec: 622490916 }
0s 35ms TRACE [LossRecovery] timeout Instant { tv_sec: 5648807, tv_nsec: 122490916 }
0s 35ms TRACE detect lost ap: now=Instant { tv_sec: 5648807, tv_nsec: 122490916 } delay=112.5ms
0s 35ms TRACE detect lost hs: now=Instant { tv_sec: 5648807, tv_nsec: 122490916 } delay=112.5ms
0s 35ms TRACE lost=11, time sent Instant { tv_sec: 5648806, tv_nsec: 822490916 } is before lost_delay 112.5ms
0s 35ms DEBUG packet_lost this=0x600002f741e0, pn=11, ps=675
0s 35ms DEBUG [NewReno CongCtrl 662/2674 ssthresh 2674] Cong event -> recovery; cwnd 2674, ssthresh 2674
0s 35ms DEBUG [NewReno CongCtrl 662/2674 ssthresh 2674] state -> RecoveryStart
0s 35ms DEBUG on_packets_lost this=0x600002f741e0, bytes_in_flight=662, cwnd=2674, state=RecoveryStart
0s 35ms TRACE detect lost in: now=Instant { tv_sec: 5648807, tv_nsec: 122490916 } delay=112.5ms
0s 35ms TRACE lost=11, time sent Instant { tv_sec: 5648806, tv_nsec: 822490916 } is before lost_delay 112.5ms
0s 35ms DEBUG packet_lost this=0x600002f741e0, pn=11, ps=662
0s 35ms DEBUG on_packets_lost this=0x600002f741e0, bytes_in_flight=0, cwnd=2674, state=RecoveryStart
0s 35ms DEBUG [Server c11688b68f20d6a8b4f512e565e90a] Lost: Crypto(CryptoRecoveryToken { space: Handshake, offset: 0, length: 628 })
0s 35ms INFO Lost crypto frame space=hs offset=0 length=628
0s 35ms DEBUG [Server c11688b68f20d6a8b4f512e565e90a] Lost: Crypto(CryptoRecoveryToken { space: Initial, offset: 0, length: 90 })
0s 35ms INFO Lost crypto frame space=in offset=0 length=90
0s 35ms TRACE [Server c11688b68f20d6a8b4f512e565e90a] output Instant { tv_sec: 5648807, tv_nsec: 122490916 }
0s 35ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 5648807, tv_nsec: 122490916 }
0s 35ms DEBUG [Server c11688b68f20d6a8b4f512e565e90a] output_path send_profile SendProfile { limit: 255, pto: None, probe: (), paced: false }
0s 35ms DEBUG Building Initial dcid 0900000000c1f2c64a scid 0800000000c32312
0s 35ms DEBUG Building Handshake dcid 0900000000c1f2c64a scid 0800000000c32312
0s 35ms DEBUG Building Short dcid 0900000000c1f2c64a
0s 35ms DEBUG TX blocked, profile=SendProfile { limit: 255, pto: None, probe: (), paced: false }
0s 35ms TRACE [Server c11688b68f20d6a8b4f512e565e90a] Get callback delay Instant { tv_sec: 5648807, tv_nsec: 122490916 }
0s 35ms TRACE ack_time for ap = None
0s 35ms TRACE ack_time for hs = None
0s 35ms TRACE ack_time for in = None
0s 35ms TRACE IdleTimeout::expiry@Instant { tv_sec: 5648807, tv_nsec: 122490916 } pto=325ms, ka=false => Instant { tv_sec: 610448805, tv_nsec: 622490916 }
0s 35ms TRACE [Server c11688b68f20d6a8b4f512e565e90a] Idle/keepalive timer Instant { tv_sec: 610448805, tv_nsec: 622490916 }
0s 35ms TRACE [LossRecovery] next_timeout loss=None pto=Some(Instant { tv_sec: 5648807, tv_nsec: 122490916 })
0s 35ms TRACE [Server c11688b68f20d6a8b4f512e565e90a] Loss recovery timer Instant { tv_sec: 5648807, tv_nsec: 122490916 }
thread 'idle_timeout_crazy_rtt' panicked at neqo-transport/src/connection/mod.rs:1068:9:
assertion failed: earliest > now
```

**Comment by KershawChang** [comment]
> @martinthomson @KershawChang if any of you understands the timer code, I'd appreciate some help here. The `idle_timeout_crazy_rtt` persistently crashes with `assertion failed: earliest > now`, which seems to be a long-standing issue.
> 

I think we need to implement what Matine suggested to do in this [comment](https://github.com/mozilla/neqo/pull/1491#issuecomment-1813399990).
I'll try to give it a shot.
In order to unblock this, maybe we can remove that debug assertion first?

**Comment by larseggert** [comment]
> In order to unblock this, maybe we can remove that debug assertion first?

The it dies here
```
thread 'idle_timeout_crazy_rtt' panicked at test-fixture/src/sim/mod.rs:202:25:
assertion `left != right` failed
  left: 0ns
 right: 0ns
 ```
 And when I take that out, too, it spins forever.

File: neqo-transport/src/recovery/mod.rs [hunk 5]
```diff
@@ -828,7 +828,12 @@ impl LossRecovery {
     /// When it has, mark a few packets as "lost" for the purposes of having frames
     /// regenerated in subsequent packets.  The packets aren't truly lost, so
     /// we have to clone the `SentPacket` instance.
-    fn maybe_fire_pto(&mut self, rtt: &RttEstimate, now: Instant, lost: &mut Vec<SentPacket>) {
+    fn maybe_fire_pto(&mut self, primary_path: &PathRef, now: Instant, lost: &mut Vec<SentPacket>) {
+        let path = primary_path.borrow();
+        if !path.is_valid() {
+            return;
```
Comment (KershawChang) [inline neqo-transport/src/recovery/mod.rs:834]: Sorry, I just realized that the root cause of this PR is not the same as #1491 .
That assertion `earliest > now` is caused by this line. If I remove the early return, the test `idle_timeout_crazy_rtt` passes.

I am still looking into why this change can trigger that assertion.

Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:834]: @KershawChang any insights?

Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:834]: @KershawChang ping?

Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:834]: I just tried this (i.e., removing the early return) and while that satisfies the `earliest > now` assertion, the `loss_time_past_largest_acked` test now fails:
```
thread 'connection::tests::recovery::loss_time_past_largest_acked' panicked at neqo-transport/src/connection/tests/recovery.rs:587:5:
assertion `left != right` failed
  left: 0ns
 right: 0ns
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<core::time::Duration, core::time::Duration>
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:364:5
   4: neqo_transport::connection::tests::recovery::loss_time_past_largest_acked
             at ./src/connection/tests/recovery.rs:587:5
   5: neqo_transport::connection::tests::recovery::loss_time_past_largest_acked::{closure#0}
             at ./src/connection/tests/recovery.rs:560:34
   6: <neqo_transport::connection::tests::recovery::loss_time_past_largest_acked::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
             ```

Comment (KershawChang) [reply neqo-transport/src/recovery/mod.rs:834]: Sorry, I haven't made much progress. I'll try to look at this again this week.

Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs]: I think I have a fix for the test (similar to how I needed to fix another test in this PR).

**Comment by larseggert** [comment]
This again is waiting for a fix to the `idle_timeout_crazy_rtt` test failure.

**Comment by KershawChang** [comment]
I've tried to give this another look and I found that the problem might be about when the function `discard_packet` is called.

https://github.com/mozilla/neqo/blob/e2fc9b0392972f9c37e78ea1d6ec4dd307267a58/neqo-transport/src/path.rs#L948

Before this change, the server was able to update the RTT to the value set [here](https://github.com/mozilla/neqo/blob/e2fc9b0392972f9c37e78ea1d6ec4dd307267a58/neqo-transport/tests/network.rs#L69)
```
0s326ms INFO [pri-unv-path:090000000037faf420 [fe80::1]:443->[fe80::1]:443] discarding a packet without an RTT estimate; guessing RTT=2999654.700000001s
```

With this change, the server can only update the RTT to a small value:
```
0s202ms INFO [pri-unv-path:0800000000b3b9a6 [fe80::1]:443->[fe80::1]:443] discarding a packet without an RTT estimate; guessing RTT=300.000001ms
```

Unfortunately, I still can't figure out the correct way to fix this.

**Comment by larseggert** [comment]
> With this change, the server can only update the RTT to a small value:
> 
> ```
> 0s202ms INFO [pri-unv-path:0800000000b3b9a6 [fe80::1]:443->[fe80::1]:443] discarding a packet without an RTT estimate; guessing RTT=300.000001ms
> ```

I don't see this log line when I run the test for this PR? (I do see the one for the `main` branch.)

> Unfortunately, I still can't figure out the correct way to fix this.

What seems to happen is that `set_valid()` is never called on the server-side for the initial path, because this patch moves that to after the path is actually validated. So the server stays amplification-limited. I'm not sure how that would affect the timers though.

**Comment by larseggert** [comment]
Some QNS L1/C1 tests are failing because #1981 is needed.

File: neqo-transport/src/recovery/mod.rs [hunk 6]
```diff
@@ -835,7 +840,9 @@ impl LossRecovery {
     /// When it has, mark a few packets as "lost" for the purposes of having frames
     /// regenerated in subsequent packets.  The packets aren't truly lost, so
     /// we have to clone the `SentPacket` instance.
-    fn maybe_fire_pto(&mut self, rtt: &RttEstimate, now: Instant, lost: &mut Vec<SentPacket>) {
+    fn maybe_fire_pto(&mut self, primary_path: &PathRef, now: Instant, lost: &mut Vec<SentPacket>) {
+        let path = primary_path.borrow();
+        let rtt = path.rtt();
```
Comment (mxinden) [inline neqo-transport/src/recovery/mod.rs:845]: Why is this change needed? Compiles and tests succeed without it on my local machine.

**Review by mxinden — APPROVED** [review]
Change makes sense to me. One minor comment.

File: neqo-transport/src/recovery/mod.rs (hunk 6 above)
Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:845]: Might be a leftover from a previous change. Let me check.

**Comment by larseggert** [comment]
So this seems to work, in the sense that there are no more `A` failures when we are the server.

But maybe there are also more `L1` and `C1` failures now, and possibly more frequent deadlocks (= runs that get cancelled by the timeout)?

It's difficult to say something definitive here, since we have had these occur randomly all along, and they may also not be due to bugs on our end.

File: neqo-transport/src/connection/mod.rs [hunk 7]
```diff
@@ -1664,7 +1664,9 @@ impl Connection {
                     .clone(),
             ),
         );
-        path.borrow_mut().set_valid(now);
+        if self.role == Role::Client {
```
[the remark this answers is not in the document]
Comment (martinthomson) [reply neqo-transport/src/connection/mod.rs:1667]: That is because this code is called by both roles, but only the client should start with the assumption that the path is OK.

File: neqo-transport/src/recovery/mod.rs [hunk 8]
```diff
@@ -735,9 +735,14 @@ impl LossRecovery {
 
     /// Calculate when the next timeout is likely to be.  This is the earlier of the loss timer
     /// and the PTO timer; either or both might be disabled, so this can return `None`.
```
Comment (martinthomson) [inline neqo-transport/src/recovery/mod.rs:737]: This probably needs to be updated.

File: neqo-transport/src/recovery/mod.rs [hunk 9]
```diff
@@ -735,9 +735,14 @@ impl LossRecovery {
...
-    pub fn next_timeout(&self, rtt: &RttEstimate) -> Option<Instant> {
+    pub fn next_timeout(&self, path: &Path) -> Option<Instant> {
+        let rtt = path.rtt();
         let loss_time = self.earliest_loss_time(rtt);
-        let pto_time = self.earliest_pto(rtt);
+        let pto_time = if path.amplification_limit() > path.plpmtu() {
```
Comment (martinthomson) [inline neqo-transport/src/recovery/mod.rs:741]: This condition seems like it should be encapsulated better.  In a is_validated() function or something.

File: neqo-transport/src/recovery/mod.rs (hunk 8 above)
Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:737]: What should it say instead? The
> either or both might be disabled, so this can return `None`

bit seems to cover what happens, even with the change?

File: neqo-transport/src/recovery/mod.rs (hunk 9 above)
Comment (larseggert) [reply neqo-transport/src/recovery/mod.rs:741]: There is `is_valid()`, but this condition isn't quite the same as `!is_valid()`, since we can also PTO on a path that is not yet validated but where we have sent less than the amplification limit.

How about this?

```suggestion
        let pto_time = if path.is_valid() || path.amplification_limit() > path.plpmtu() {
```

Makes it a bit clearer and we don't need to run through `amplification_limit()` in the common case.

File: neqo-transport/src/recovery/mod.rs (hunk 8 above)
Comment (martinthomson) [reply neqo-transport/src/recovery/mod.rs:737]: Yeah, you are right.  Nevermind.

File: neqo-transport/src/recovery/mod.rs (hunk 9 above)
Comment (martinthomson) [reply neqo-transport/src/recovery/mod.rs:741]: That would help, but it might be better to encapsulate that check.

```rust
impl Path {
/// Determine whether we should be setting a PTO for this path.
/// This is true when either the path is valid or when there is enough
/// remaining in the amplification limit to fit a full-sized path (i.e., the path MTU).
pub fn pto_enabled(&self) -> bool {
  // See the implementation `amplification_limit` for details.
  self.amplification_limit() >= self.plpmtu()
}
```

**Review by martinthomson — APPROVED** [review]
