### PR TITLE
fix: Check whether CIDs are empty

### LINKED ISSUE #1429: Crash in [@ neqo_transport::connection::Connection::build_packet_header]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1829989.

The crash reason is `called `Option::unwrap()` on a `None` value`.
Crash stack:

8 | libxul.so | core::panicking::panic | library/core/src/panicking.rs:114 | cfi
-- | -- | -- | -- | --
9 | libxul.so | neqo_transport::connection::Connection::build_packet_header | third_party/rust/neqo-transport/src/packet/mod.rs:0 | cfi
10 | libxul.so | neqo_transport::connection::Connection::output_close | third_party/rust/neqo-transport/src/connection/mod.rs:1850 | inlined
10 | libxul.so | neqo_transport::connection::Connection::output | third_party/rust/neqo-transport/src/connection/mod.rs:1760 | inlined
10 | libxul.so | neqo_transport::connection::Connection::process_output | third_party/rust/neqo-transport/src/connection/mod.rs:1004 | cfi
11 | libxul.so | neqo_http3::connection_client::Http3Client::process_output | third_party/rust/neqo-http3/src/connection_client.rs:850

It's not clear to me where `unwrap` is called inside function `build_packet_header`. Maybe @martinthomson knows?

### PR DESCRIPTION
**Pull request by larseggert**
Avoid `unwrap` calls when accessing connection IDs.

Fixes #1429

### CODE REVIEW

File: neqo-transport/src/connection/mod.rs [hunk 1]
```diff
@@ -1931,18 +1931,18 @@ impl Connection {
         grease_quic_bit: bool,
     ) -> (PacketType, PacketBuilder) {
         let pt = PacketType::from(cspace);
+        let dcid = path
+            .remote_cid()
+            .map_or(Vec::new(), |id| id.as_ref().to_vec());
```
Comment (martinthomson) [inline neqo-transport/src/connection/mod.rs:1936]: You shouldn't need to allocate a new `Vec` here.  I would suggest changing the signature of `PacketBuilder::short`/`PacketBuilder::long` instead so that they take `Option<impl AsRef<[u8]>`.  You can call on that with `if let Some(...)` or `dcid.map_or(&[], AsRef::as_ref)` or `dcid.map_or(0, |d| d.as_ref().len())` as necessary.

**Review by martinthomson — CHANGES_REQUESTED** [review]

**Review by KershawChang — APPROVED** [review]

File: neqo-transport/src/qlog.rs [hunk 2]
```diff
@@ -104,8 +104,8 @@ fn connection_started(qlog: &NeqoQlog, path: &PathRef) {
             protocol: Some("QUIC".into()),
             src_port: p.local_address().port().into(),
             dst_port: p.remote_address().port().into(),
-            src_cid: Some(format!("{}", p.local_cid())),
-            dst_cid: Some(format!("{}", p.remote_cid())),
+            src_cid: p.local_cid().map(|id| format!("{id}")),
+            dst_cid: p.remote_cid().map(|id| format!("{id}")),
```
Comment (mxinden) [inline neqo-transport/src/qlog.rs:108]: Nit, only related to this pull request:

`ConnectionId` implements `Display`. Instead of going through the full string interpolation macro `format!`, one might as well just call `ToString::to_string`:



```suggestion
            src_cid: p.local_cid().map(ToString::to_string),
            dst_cid: p.remote_cid().map(ToString::to_string),
```

See also https://doc.rust-lang.org/std/string/trait.ToString.html.

Intuitively, I would expect `ToString` to be faster than `format!`. Though that would need a benchmark proof.

Feel free to ignore.

File: neqo-transport/src/packet/mod.rs [hunk 3]
```diff
@@ -149,15 +149,19 @@ impl PacketBuilder {
     ///
     /// If, after calling this method, `remaining()` returns 0, then call `abort()` to get
     /// the encoder back.
-    pub fn short(mut encoder: Encoder, key_phase: bool, dcid: impl AsRef<[u8]>) -> Self {
+    pub fn short(mut encoder: Encoder, key_phase: bool, dcid: &Option<impl AsRef<[u8]>>) -> Self {
```
Comment (mxinden) [inline neqo-transport/src/packet/mod.rs:152]:
```suggestion
    pub fn short(mut encoder: Encoder, key_phase: bool, dcid: Option<impl AsRef<[u8]>>) -> Self {
```

A reference to an option containing a reference seems unnecessary. Would the above work?

File: neqo-transport/src/packet/mod.rs [hunk 4]
```diff
@@ -185,20 +189,23 @@ impl PacketBuilder {
         mut encoder: Encoder,
         pt: PacketType,
         version: Version,
-        dcid: impl AsRef<[u8]>,
-        scid: impl AsRef<[u8]>,
+        dcid: &Option<impl AsRef<[u8]>>,
+        scid: &Option<impl AsRef<[u8]>>,
```
Comment (mxinden) [inline neqo-transport/src/packet/mod.rs:193]: Same as above.

```suggestion
        dcid: Option<impl AsRef<[u8]>>,
        scid: Option<impl AsRef<[u8]>>,
```

File: neqo-transport/src/connection/mod.rs [hunk 5]
```diff
@@ -1908,7 +1912,7 @@ impl Connection {
                         // a packet on a new path, we avoid sending (and the privacy risk) rather
                         // than reuse a connection ID.
                         let res = if path.borrow().is_temporary() {
-                            assert!(!cfg!(test), "attempting to close with a temporary path");
+                            debug_assert!(!cfg!(test), "attempting to close with a temporary path");
                             Err(Error::InternalError)
```
Comment (mxinden) [inline neqo-transport/src/connection/mod.rs:1916]: Bubbling  `Error::InternalError` up multiple levels will have it loose semantic context, in other words, we won't know what exactly failed from the outside.

I suggest either logging here, or, long term, we might want to consider embracing [Rust's Error backtraces](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.provide) via `thiserror` or [`snafu`](https://docs.rs/snafu/latest/snafu/). Though at least the former still depends on Rust Nightly.

**Review by mxinden — APPROVED** [review]
Couple of smaller comments. Overall this looks good to me.

File: neqo-transport/src/packet/mod.rs (hunk 3 above)
Comment (larseggert) [reply neqo-transport/src/packet/mod.rs:152]: I tried that first, but then clippy told me `this argument is passed by value, but not consumed in the function body`.

Comment (larseggert) [reply neqo-transport/src/packet/mod.rs:152]: @mxinden any idea for how to fix this? (My Rust-fu isn't sufficient.)

Comment (mxinden) [reply neqo-transport/src/packet/mod.rs:152]: I am having difficulties reproducing the clippy failure on https://github.com/larseggert/neqo/pull/28.

@larseggert can you share your clippy version?

```
➜  cargo clippy --version
clippy 0.1.80 (0514789 2024-07-21)
```

Comment (larseggert) [reply neqo-transport/src/packet/mod.rs]: Same.

Comment (mxinden) [reply neqo-transport/src/packet/mod.rs]: Let's see what CI says to https://github.com/mozilla/neqo/pull/2034/commits/3903db63fecab90228656bee50e27ca3d68c8708.

Comment (larseggert) [reply neqo-transport/src/packet/mod.rs]: I think I worked around this with `take()`; please take a look?

**Review by mxinden — APPROVED** [review]
