### PR TITLE
fix: Don't prime the handshake PTO w/o keys

### LINKED ISSUE #3410: Don't prime the handshake PTO w/o keys
This might prime the handshake PTO even if we have no Handshake keys available, right?

Sample scenario:

1. Client sends ClientHello split across two Initial packets
2. Server receives only the first packet, cannot complete TLS, sends a bare ACK.
3. Client receives the ACK for second packet.
4. Client Initial PTO fires
5. `maybe_prime_handshake_pto` primes handshake PTO even though the client has no Handshake TX keys (ServerHello was never received).
6. Handshake PTO fires (potentially in the past), but we can not act on it.

Is the above correct @larseggert? What do you think of only calling `maybe_prime_handshake_pto` if we have handshake space keys to actually send anything.

This would fix https://github.com/mozilla/neqo/pull/3408 and thus also fix (at least one case of) https://bugzilla.mozilla.org/show_bug.cgi?id=2001901.

_Originally posted by @mxinden in https://github.com/mozilla/neqo/pull/3097#discussion_r2874486815_

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #3410

### CODE REVIEW

File: neqo-transport/src/connection/tests/recovery.rs [hunk 1]
```diff
@@ -1032,6 +1032,50 @@ fn pto_handshake_space_when_server_flight_lost() {
...
+/// `pto_state` and the stale Handshake PTO fires in the past.
+#[test]
+fn handshake_pto_not_primed_without_keys() {
+    let mut now = now();
+    let mut client = new_client(ConnectionParameters::default().pacing(false));
+    let mut server = new_server(ConnectionParameters::default().pacing(false));
+
+    // Split ClientHello across two Initial packets (MLKEM).
+    let c_init_1 = client.process_output(now).dgram().unwrap();
+    assert!(client.process_output(now).dgram().is_some()); // c_init_2, intentionally dropped
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/recovery.rs]: Copilot is sort of correct here.  This should assert that the second datagram indeed starts with an Initial.

File: neqo-transport/src/connection/tests/recovery.rs [hunk 2]
```diff
@@ -1032,6 +1032,50 @@ fn pto_handshake_space_when_server_flight_lost() {
...
+
+    // Deliver only c_init_1.  Incomplete CH → server sends bare ACK.
+    now += DEFAULT_RTT / 2;
+    server.process_input(c_init_1, now);
+    let s_ack = server.process_output(now).dgram().unwrap();
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/recovery.rs]: collapse these two into a single "process()" call

File: neqo-transport/src/connection/tests/recovery.rs [hunk 3]
```diff
@@ -1032,6 +1032,50 @@ fn pto_handshake_space_when_server_flight_lost() {
...
+
+    // Two PTO iterations (output dropped) push Initial baseline ahead of the
+    // Handshake baseline that was primed during iteration 1.
+    for _ in 0..2 {
+        now += client.process_output(now).callback();
+        while client.process_output(now).dgram().is_some() {}
+    }
+
+    // Third PTO: deliver the PING so the server ACKs it, clearing pto_state.
+    now += client.process_output(now).callback();
```
[the remark this answers is not in the document]
Comment (martinthomson) [reply neqo-transport/src/connection/tests/recovery.rs]: Copilot is right to ask that the value isn't zero.  I don't like it's suggested code.

**Review by martinthomson — COMMENTED** [review]
The agents might not be quite ready to take our jobs, but this is a good find.
