### PR TITLE
test: Dump simulator RNG seeds

### LINKED ISSUE #1645: Output seed to stdout for tests
This is harder than it sounds.

The "simulator" we use in some of our randomized tests uses a random seed.  The idea is that if a random test fails, we could take that seed and reproduce the exact failure conditions again to debug them.  Originally, this seed was printed to stdout, which would be captured by the test runner, then later validated.  Unfortunately, when I used the same code for benchmarking, stdout was not captured.  I had to suppress this message.

Ideally, if we are benchmarking, we would suppress this output, but in regular test runs we wouldn't.  It is possible that we could test `debug_assertions` for this on that basis that benchmarks run in release mode and tests run in debug mode, but I'm not 100% confident that this is the right way to do that.

### PR DESCRIPTION
**Pull request by larseggert**
Into the directory given in the `DUMP_SIMULATION_SEEDS` environment variable. Also, export them as artifacts from the CI runs.

Fixes #1645

### CODE REVIEW

File: test-fixture/src/sim/mod.rs [hunk 1]
```diff
@@ -151,23 +148,37 @@ impl Simulator {
...
-    pub fn seed(&mut self, seed: [u8; 32]) {
-        self.rng = Rc::new(RefCell::new(Random::new(&seed)));
+        // Dump the seed to a file to the directory in the `DUMP_SIMULATION_SEEDS` environment
+        // variable, if set.
+        if let Ok(dir) = std::env::var("DUMP_SIMULATION_SEEDS") {
+            if create_dir_all(&dir).is_err() {
+                qerror!("Failed to create directory {dir}");
+            } else {
+                let seed_str = sim.rng.borrow().seed_str();
+                let path = format!("{dir}/{seed_str}");
```
Comment (mxinden) [inline test-fixture/src/sim/mod.rs:167]: Instead of manual path formatting, I prefer to use [`PathBuf`](https://doc.rust-lang.org/std/path/struct.PathBuf.html), taking care of all the idiosyncrasies of the various platforms.

**Review by mxinden — APPROVED** [review]
Just

File: .github/workflows/check.yml [hunk 2]
```diff
@@ -118,9 +121,25 @@ jobs:
...
+            if [ "${{ env.DUMP_SIMULATION_SEEDS }}" ]; then
+              export DUMP_SIMULATION_SEEDS="${{ env.DUMP_SIMULATION_SEEDS }}/sanitizer/$sanitizer"
+            fi
             RUSTFLAGS="-Z sanitizer=$sanitizer" RUSTDOCFLAGS="-Z sanitizer=$sanitizer" cargo +nightly nextest run -Z build-std --features ci --target "$TARGET"
           done
 
+      - name: Print simulation seeds
+        if: env.DUMP_SIMULATION_SEEDS
+        run: find ${{ env.DUMP_SIMULATION_SEEDS }}
+
```
Comment (martinthomson) [inline .github/workflows/check.yml:134]: Presumably you don't need this...

```suggestion
```

File: .github/workflows/check.yml [hunk 3]
```diff
@@ -68,12 +69,14 @@ jobs:
           cargo +${{ matrix.rust-toolchain }} check $BUILD_TYPE --all-targets --features ci
 
       - name: Run tests and determine coverage
+        env:
+          RUST_LOG: trace
```
Comment (martinthomson) [inline .github/workflows/check.yml:73]: Do you need this?

File: test-fixture/src/sim/rng.rs [hunk 4]
```diff
@@ -69,8 +69,9 @@ impl Random {
     /// Get the seed necessary to continue from the current state of the RNG.
     #[must_use]
     pub fn seed_str(&self) -> String {
+        // Make sure to print leading zeros.
```
Comment (martinthomson) [inline test-fixture/src/sim/rng.rs:72]:
```suggestion
```

File: test-fixture/src/sim/mod.rs [hunk 5]
```diff
@@ -151,23 +148,37 @@ impl Simulator {
...
+                if write(&path, seed_str).is_err() {
+                    qerror!("Failed to write seed to {path}");
```
Comment (martinthomson) [inline test-fixture/src/sim/mod.rs:169]:
```suggestion
                    qerror!("Simulation seed: {seed_str}");
```
Might as well just print the value out here.

File: test-fixture/src/sim/mod.rs [hunk 6]
```diff
@@ -151,23 +148,37 @@ impl Simulator {
...
-        self.rng = Rc::new(RefCell::new(Random::new(&seed)));
+        // Dump the seed to a file to the directory in the `DUMP_SIMULATION_SEEDS` environment
+        // variable, if set.
+        if let Ok(dir) = std::env::var("DUMP_SIMULATION_SEEDS") {
+            if create_dir_all(&dir).is_err() {
+                qerror!("Failed to create directory {dir}");
+            } else {
+                let seed_str = sim.rng.borrow().seed_str();
+                let path = format!("{dir}/{seed_str}");
+                if write(&path, seed_str).is_err() {
```
Comment (martinthomson) [inline test-fixture/src/sim/mod.rs:168]: If the filename is the seed, why bother with putting anything in it?

```suggestion
                if File::create(&path).is_err() {
```

File: .github/workflows/check.yml (hunk 2 above)
Comment (larseggert) [reply .github/workflows/check.yml:134]: Not strictly, since we also provide them as artifacts.

File: test-fixture/src/sim/mod.rs (hunk 5 above)
Comment (larseggert) [reply test-fixture/src/sim/mod.rs:169]: It's being printed elsewhere already.

File: test-fixture/src/sim/mod.rs (hunk 6 above)
Comment (larseggert) [reply test-fixture/src/sim/mod.rs:168]: I find it sometimes easier to `cat` than to `ls` when scripting.

File: .github/workflows/check.yml (hunk 3 above)
Comment (larseggert) [reply .github/workflows/check.yml:73]: We do need to set the env variable, so debug-output-producing code is getting coverage-tested. But we can also set that on each run like before, in case that is what you meant?

**Review by martinthomson — APPROVED** [review]

**Comment by mxinden** [comment]
@larseggert do you recall why this is dumping to a file, instead of printing to stdout? We would thus not need an artifact CI step, but can just read the seed from the logs. Debugging #2499 I noticed we don't dump nor artifact the seed for the benchmarks.

**Comment by larseggert** [comment]
I can't recall. Am OK with changing to a debug output.
