### PR TITLE
fix: Include an ACK with a CONNECTION_CLOSE

### LINKED ISSUE #1161: Send ACK with CONNECTION_CLOSE
Servers have observed that reducing ACK frequency increases the probability that clients that close connections without acknowledging some packets.  We could help a little here by sending acknowledgments in the CONNECTION_CLOSE.  The code should be reusable.  Tweaking tests might be a fun exercise, but there aren't that many tests for connection closing, so it might not be too bad.

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #1161

### CODE REVIEW

File: neqo-transport/src/connection/tests/close.rs [hunk 1]
```diff
@@ -40,7 +40,11 @@ fn connection_close() {
 
     client.close(now, 42, "");
 
+    let stats_before = client.stats().frame_tx;
     let out = client.process(None, now);
+    let stats_after = client.stats().frame_tx;
+    assert!(stats_after.connection_close == stats_before.connection_close + 1);
```
Comment (mxinden) [inline neqo-transport/src/connection/tests/close.rs:46]:
```suggestion
    assert_eq!(stats_after.connection_close. stats_before.connection_close + 1);
```

Nit: would print both values on failure, making debugging easier.

File: neqo-transport/src/connection/tests/close.rs [hunk 2]
```diff
@@ -40,7 +40,11 @@ fn connection_close() {
...
+    assert!(stats_after.ack == stats_before.ack + 1);
```
Comment (mxinden) [inline neqo-transport/src/connection/tests/close.rs:47]:
```suggestion
    assert_eq!(stats_after.ack, stats_before.ack + 1);
```

File: neqo-transport/src/connection/tests/close.rs [hunk 3]
```diff
@@ -57,7 +61,11 @@ fn connection_close_with_long_reason_string() {
     let long_reason = String::from_utf8([0x61; 2048].to_vec()).unwrap();
     client.close(now, 42, long_reason);
 
+    let stats_before = client.stats().frame_tx;
     let out = client.process(None, now);
+    let stats_after = client.stats().frame_tx;
+    assert!(stats_after.connection_close == stats_before.connection_close + 1);
```
Comment (mxinden) [inline neqo-transport/src/connection/tests/close.rs:67]:
```suggestion
    assert_eq!(stats_after.connection_close, stats_before.connection_close + 1);
```

File: neqo-transport/src/connection/tests/close.rs [hunk 4]
```diff
@@ -57,7 +61,11 @@ fn connection_close_with_long_reason_string() {
...
+    assert!(stats_after.ack == stats_before.ack + 1);
```
Comment (mxinden) [inline neqo-transport/src/connection/tests/close.rs:68]:
```suggestion
    assert_eq!(stats_after.ack. stats_before.ack + 1);
```

**Review by mxinden — COMMENTED** [review]
Potentially silly question, does the order matter? In other words, do some servers ignore ack frames after a closing frame?

**Review by mxinden — COMMENTED** [review]
~Potentially silly question, does the order matter? In other words, do some servers ignore ack frames after a closing frame?~

Edit: Spotty internet connection on train.

File: neqo-transport/src/connection/mod.rs [hunk 5]
```diff
@@ -2252,6 +2252,18 @@ impl Connection {
             let payload_start = builder.len();
             let (mut tokens, mut ack_eliciting, mut padded) = (Vec::new(), false, false);
             if let Some(ref close) = closing_frame {
+                if builder.remaining() > ClosingFrame::min_length() + RecvdPackets::max_len() {
```
Comment (martinthomson) [inline neqo-transport/src/connection/mod.rs:2255]: This little chunk of code (under `if let Some(ref close) ...` is large enough now that it probably needs its own function.

As for this line of code, I think that what you want to do is ask the closing frame how much space it is going to take up, then - if there is enough space for a minimal ACK, which might assume ECN for the sake of simplicity - you would temporarily reduce "remaining" by the closing frame size, write the ACK, add back the closing frame size, and off you go.

The close frame size computation doesn't need to take "remaining" into account.  We just need to know how big it would prefer to be.

File: neqo-transport/src/tracking.rs [hunk 6]
```diff
@@ -559,6 +559,12 @@ impl RecvdPackets {
         }
     }
 
+    pub const fn max_len() -> usize {
+        // The worst possible ACK frame, assuming only one range.
+        // Note that this assumes one byte for the type and count of extra ranges.
+        1 + 8 + 8 + 1 + 8
+    }
```
Comment (martinthomson) [inline neqo-transport/src/tracking.rs:566]: This can be a constant on the type rather than a function.

File: neqo-transport/src/connection/state.rs [hunk 7]
```diff
@@ -156,10 +156,14 @@ impl ClosingFrame {
         }
     }
 
-    pub fn write_frame(&self, builder: &mut PacketBuilder) {
+    pub const fn min_length() -> usize {
```
Comment (martinthomson) [inline neqo-transport/src/connection/state.rs:159]: A constant would be better.

File: neqo-transport/src/connection/tests/close.rs [hunk 8]
```diff
@@ -57,7 +64,14 @@ fn connection_close_with_long_reason_string() {
...
     client.close(now, 42, long_reason);
 
+    let stats_before = client.stats().frame_tx;
     let out = client.process(None, now);
+    let stats_after = client.stats().frame_tx;
+    assert_eq!(
+        stats_after.connection_close,
+        stats_before.connection_close + 1
+    );
+    assert_eq!(stats_after.ack, stats_before.ack + 1);
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/close.rs:74]: Why are you seeing an ACK sent in this case?  I thought that the close would squeeze out the ACK.

File: neqo-transport/src/connection/mod.rs [hunk 9]
```diff
@@ -2252,6 +2274,10 @@ impl Connection {
             let payload_start = builder.len();
             let (mut tokens, mut ack_eliciting, mut padded) = (Vec::new(), false, false);
             if let Some(ref close) = closing_frame {
```
Comment (martinthomson) [inline neqo-transport/src/connection/mod.rs:2276]: I was suggesting that the entirety of this block (not the inner one; down to 2265(left)/2291(right)) be moved to a `write_closing_frames` function or similar.  Maybe there are too many arguments for that to look neat, I don't know.

File: neqo-transport/src/tracking.rs [hunk 10]
```diff
@@ -559,6 +559,10 @@ impl RecvdPackets {
         }
     }
 
+    /// Length of the worst possible ACK frame, assuming only one range and ECN counts.
+    /// Note that this assumes one byte for the type and count of extra ranges.
+    pub const MAX_ACK_LEN: usize = 1 + 8 + 8 + 1 + 8 + 3 * 8;
```
Comment (martinthomson) [inline neqo-transport/src/tracking.rs:564]: I can't think of a better name, but this isn't quite right.  What you have here is the longest length that an ACK can be if it contains a single range (and ECN counts).  A useful construct, for sure, because it is the safe minimum we'd need to be able to send a useful ACK.  So maybe:

```suggestion
    pub const USEFUL_ACK_LEN: usize = 1 + 8 + 8 + 1 + 8 + 3 * 8;
```

File: neqo-transport/src/tracking.rs [hunk 11]
```diff
@@ -1158,7 +1159,7 @@ mod tests {
             .is_some());
 
         let mut builder = PacketBuilder::short(Encoder::new(), false, []);
-        builder.set_limit(32);
+        builder.set_limit(RecvdPackets::MAX_ACK_LEN + 8);
```
Comment (martinthomson) [inline neqo-transport/src/tracking.rs:1162]:
```suggestion
        // The code pessimistically assumes that each range needs 16 bytes to express.
        // So this won't be enough for a second range.
        builder.set_limit(RecvdPackets::MAX_ACK_LEN + 8);
```

**Review by martinthomson — APPROVED** [review]

File: neqo-transport/src/connection/tests/close.rs (hunk 8 above)
Comment (larseggert) [reply neqo-transport/src/connection/tests/close.rs:74]: The reason phrase is limited to 256 in https://github.com/mozilla/neqo/blob/52675c358c29a3a1c434050b93719cf88c86c61a/neqo-transport/src/connection/state.rs#L176-L183, which leaves enough space for the ACK.

Comment (martinthomson) [reply neqo-transport/src/connection/tests/close.rs:74]: Ah.  I forgot about that.  That means that we're not really testing the case where the close squeezes the ACK out.  Should we?  (Looking at the code, I don't think that we can.  I don't think we ever have more than two spaces to send a close in, and at 256 bytes, I doubt we'd hit the datagram size limit.)

Comment (larseggert) [reply neqo-transport/src/connection/tests/close.rs:74]: I don't think so either.
