### PR TITLE
fix: qpack idiomization

### LINKED ISSUE #3179: Use `HEADER_STATIC_TABLE.get().ok_or()`
FWIW, a better way to manage this is to do:

```rust
HEADER_STATIC_TABLE.get().ok_or(Error::HeaderLookup)
```

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/3174#discussion_r2570120722_

Also needs a test for the error condition.

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #3179 and rolls in one similar change.

### CODE REVIEW

File: neqo-qpack/src/table.rs [hunk 1]
```diff
@@ -254,14 +245,15 @@ impl HeaderTable {
...
+        while let Some(e) = self.dynamic.back() {
+            if self.used <= reduce {
+                break;
+            }
+            if !e.can_reduce(self.acked_inserts_cnt) {
+                return false;
             }
+            self.used -= u64::try_from(e.size()).expect("usize fits in u64");
+            self.dynamic.pop_back();
         }
```
Comment (martinthomson) [inline neqo-qpack/src/table.rs:257]: We need rust 1.93...

```suggestion
        while self.used > target { // note renamed from reduce
            let Some(e) = self.dynamic.pop_back_if(|e| e.can_reduce(self.acked_inserts_cnt)) else {
                return false;
            };
            self.used -= u64::try_from(e.size()).expect("usize fits in u64");
        }
```

As it is, I think that what you have is fine.  It's just not as idiomatic as you might like.
