### PR TITLE
fix: Don't allow migration if the peer doesn't allow it

### LINKED ISSUE #2103: Make `Connection::migrate` fail when server doesn't support  active migration
One thing I noticed is that we have a public method called "migrate" on the connection.  This method can be called when the server has set `disable_active_migration`.  That's not ideal.  That's worth another change, I think.

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/2100#pullrequestreview-2301593264_

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #2103

### CODE REVIEW

File: neqo-transport/src/connection/tests/migration.rs [hunk 1]
```diff
@@ -969,6 +971,21 @@ fn migration_invalid_state() {
         .is_err());
 }
 
+#[test]
+fn migration_disabled() {
+    let mut client = default_client();
+    let mut server = new_server(ConnectionParameters::default().disable_migration(true));
+    connect(&mut client, &mut server);
+    assert_eq!(client.state(), &State::Confirmed);
+    assert_eq!(server.state(), &State::Confirmed);
```
Comment (mxinden) [inline neqo-transport/src/connection/tests/migration.rs:980]: Isn't this already checked by `connect` above?

https://github.com/mozilla/neqo/blob/a4692b57374b46969714269b1ae1d216903b507a/neqo-transport/src/connection/tests/mod.rs#L275-L276

**Review by mxinden — APPROVED** [review]

File: neqo-transport/src/connection/tests/migration.rs (hunk 1 above)
Comment (larseggert) [reply neqo-transport/src/connection/tests/migration.rs:980]: Possibly. Copied it from another test.
