### PR TITLE
Do not calculate keepalive's timeout when a keepalive is outstanding.

### LINKED ISSUE #1359: Assertion eariest > now
I hit [this assertion](https://github.com/mozilla/neqo/blob/e71e860489447fed25b64bd8ec31a804dccb0dad/neqo-transport/src/connection/mod.rs#L976) while working with firefox. 
I think the reason was that the server stopped responding and i think sam pings have a wrong sent time or something. First, I need to try to recreate the test case using only neqo.

### PR DESCRIPTION
**Pull request by ddragana**
Fixes #1359

### CODE REVIEW

**Comment by ddragana** [comment]
If an ack-eliciting packet is outstanding and we send a keepalive packet, the IdleTimeoutState will not change, therefore anytime we calculate the keepalive timer it will return the same time as when the keepalive packet has been sent which is in the past.

File: neqo-http3/tests/httpconn.rs [hunk 1]
```diff
@@ -379,3 +412,45 @@ fn zerortt() {
...
 }
+
+#[test]
+fn test_fetch_noresponse_will_idletimeout() {
+    let mut hconn_c = default_http3_client();
+    let mut hconn_s = default_http3_server();
+
+    let (dgram, mut now) = connect_peers_with_rtt(&mut hconn_c, &mut hconn_s, 10);
+
+    eprintln!("-----client");
```
Comment (martinthomson) [inline neqo-http3/tests/httpconn.rs:423]: Use `qtrace!()` for these.

File: neqo-http3/tests/httpconn.rs [hunk 2]
```diff
@@ -111,6 +112,38 @@ fn connect_peers(hconn_c: &mut Http3Client, hconn_s: &mut Http3Server) -> Option
     out.dgram()
 }
 
+fn connect_peers_with_rtt(
+    hconn_c: &mut Http3Client,
+    hconn_s: &mut Http3Server,
+    net_delay: u64,
+) -> (Option<Datagram>, Instant) {
+    let net_delay = Duration::from_millis(net_delay);
```
Comment (martinthomson) [inline neqo-http3/tests/httpconn.rs:120]: API quibble: you are using `net_delay`, which is the one way propagation delay rather than RTT, but the function is named "\_with\_rtt".

File: neqo-http3/tests/httpconn.rs [hunk 3]
```diff
@@ -111,6 +112,38 @@ fn connect_peers(hconn_c: &mut Http3Client, hconn_s: &mut Http3Server) -> Option
...
+    assert_eq!(hconn_c.state(), Http3State::Initializing);
+    let mut now = now();
+    let out = hconn_c.process(None, now); // Initial
+    now += net_delay;
+    let out = hconn_s.process(out.dgram(), now); // Initial + Handshake
+    now += net_delay;
+    let out = hconn_c.process(out.dgram(), now); // ACK
+    now += net_delay;
+    mem::drop(hconn_s.process(out.dgram(), now)); //consume ACK
```
Comment (martinthomson) [inline neqo-http3/tests/httpconn.rs:129]: Rather than mem::drop() here, you should probably just use process_input() at the client, so that it doesn't generate the ACK and the server doesn't need to process it.  Then we don't drop packets in the test. Dropping stuff can affect other things, which might not alter this particular test, but it's probably worthwhile. You'll need to unwrap the datagram to do that, but I think that it's better.

You can also remove some of the extra delays then.

File: neqo-http3/tests/httpconn.rs [hunk 4]
```diff
@@ -111,6 +112,38 @@ fn connect_peers(hconn_c: &mut Http3Client, hconn_s: &mut Http3Server) -> Option
...
+    let out = hconn_c.process(None, now); // Handshake
+    assert_eq!(hconn_c.state(), Http3State::Connected);
+    now += net_delay;
+    let out = hconn_s.process(out.dgram(), now); // Handshake
+    now += net_delay;
+    let out = hconn_c.process(out.dgram(), now);
+    now += net_delay;
+    let out = hconn_s.process(out.dgram(), now);
+    now += net_delay;
+    let out = hconn_c.process(out.dgram(), now);
```
Comment (martinthomson) [inline neqo-http3/tests/httpconn.rs:143]: What do all these other ones do?  HANDSHAKE_DONE?  Control streams?

File: neqo-http3/tests/httpconn.rs [hunk 5]
```diff
@@ -379,3 +412,45 @@ fn zerortt() {
     exchange_packets(&mut hconn_c, &mut hconn_s, out.dgram());
     process_client_events(&mut hconn_c);
 }
+
+#[test]
+fn test_fetch_noresponse_will_idletimeout() {
```
Comment (martinthomson) [inline neqo-http3/tests/httpconn.rs:417]:
```suggestion
/// When a client has an outstanding fetch, it will send keepalives.
/// Test that it will successfully run until the connection times out.
fn fetch_noresponse_will_idletimeout() {
```

**Review by martinthomson — COMMENTED** [review]
Can we have a test in neqo-transport for this?  The bug is there, so we really should be testing it there as well.

File: neqo-http3/tests/httpconn.rs (hunk 3 above)
Comment (ddragana) [reply neqo-http3/tests/httpconn.rs:129]: We do not need to drop this packet because it is not a datagram. I will add an assertion.

File: neqo-http3/tests/httpconn.rs (hunk 4 above)
Comment (ddragana) [reply neqo-http3/tests/httpconn.rs:143]: I will add a description, but yes HANDSHAKE_DONE and control and qpack streams.

**Review by KershawChang — APPROVED** [review]
Looks good to me.
