### PR TITLE
Fix hframe.

### LINKED ISSUE #169: Issues with HFrameReader
There are a coupe of issues with HFrameReader:

- if a sender closes a stream before sending anything the HFrameReader will be in state GetType instead of BeforeFrame and neqo will fail reading frame with MalformatedFrame error.

- This code in fn HFrameReader::receive() is not correct:

```
            let mut input = match conn.stream_recv(stream_id, &mut buf[..]) {
                Ok((_, true)) => {
```

If stream_recv returns some data and fin we will exit the function before actually consuming the data. Therefore the HFrameREader will be in wrong state and we will report MalformatedFrame.

- If the length of a frame is 0 for some frames we change to state HFrameReaderState::GetData, but there is not more data to receive.

- Also I will move breaking out of the loop to the end of the loop so that it is consistent and at one place.

- Currently we return `break Err(Error::NoMoreData)`, if we are in state that is not the one already handled. I think we can never be in any other state than the states we already handle. I will put a panic instead of returning error.

### PR DESCRIPTION
**Pull request by ddragana**
Fixes #169.

### CODE REVIEW

File: neqo-http3/src/hframe.rs [hunk 1]
```diff
@@ -908,4 +935,213 @@ mod tests {
             panic!("wrong frame type");
         }
     }
+
+    fn test_reading_frame(
+        buf: &[u8],
+        send_fin_with_data: bool,
+        send_fin_after_data: bool,
+        expect_fin: bool,
+        succeed: bool,
```
Comment (martinthomson) [inline neqo-http3/src/hframe.rs]:
```suggestion
        expect_success: bool,
```

File: neqo-http3/src/hframe.rs [hunk 2]
```diff
@@ -908,4 +935,213 @@ mod tests {
...
+        frame_done: bool,
+    ) {
+        let (mut conn_c, mut conn_s) = connect();
+
+        // create a stream
+        let stream_id = conn_s.stream_create(StreamType::BiDi).unwrap();
+
+        let mut fr: HFrameReader = HFrameReader::new();
```
Comment (martinthomson) [inline neqo-http3/src/hframe.rs]:
```suggestion
        let mut fr = HFrameReader::new();
```

Also, you can move this down closer to where it is needed.

File: neqo-http3/src/hframe.rs [hunk 3]
```diff
@@ -908,4 +935,213 @@ mod tests {
...
+        conn_c.process(out.dgram(), now());
+
+        if send_fin_after_data {
+            conn_s.stream_close_send(stream_id).unwrap();
+            let out = conn_s.process(None, now());
+            conn_c.process(out.dgram(), now());
+        }
+
+        if succeed {
+            assert_eq!(Ok(expect_fin), fr.receive(&mut conn_c, stream_id));
```
Comment (martinthomson) [inline neqo-http3/src/hframe.rs]: Move `fr.receive` out of the if statement.

File: neqo-http3/src/hframe.rs [hunk 4]
```diff
@@ -908,4 +935,213 @@ mod tests {
             panic!("wrong frame type");
         }
     }
+
+    fn test_reading_frame(
```
Comment (martinthomson) [inline neqo-http3/src/hframe.rs]: This looks really good from a distance, but the call sites are very hard to read.  I think that you want to turn that list of 5 booleans into an options struct (or an enum for the sending options) so that the call sites can be clearer:

```rust
enum FrameReadingTestSend {
  DataOnly,
  DataWithFin,
  DataThenFin,
}

enum FrameReadingTestExpect {
  Error,
  Incomplete,
  FrameComplete,
  FrameAndStreamComplete,
}

// Then test_reading_frame(&buf[..i], false, false, false, true, false) becomes
             test_reading_frame(&buf[..i], FrameReadingTestSend::OnlyData, FrameReadingTestExpect::Incomplete); 
```

**Comment by ddragana** [comment]
> Love the added tests, but one thing I'd like to make sure is recorded somewhere is the bug that this PR is fixing. You could either open an issue and then mark this PR as fixing it, or just amend/repush the "fix hframe" commit with an explanation in the commitlog.

I have open issue #169

**Comment by ddragana** [comment]
The ci error will be fix by #170
