### PR TITLE
Fix PTO and implement a separate PTO for each PN

### LINKED ISSUE #308: PTO per PN Space
We should track a PTO timer for each space and then make sure to send a packet in that space when the matching timer fires.  Otherwise, tickling the PTO timer in 0-RTT can cause the Initial to never fire and similar sorts of problems.

### LINKED ISSUE #385: a packet with ack frames after a pto ping packet
I have not debug it yet, but what to document:
pto expires we send a packet that contains a ping,  self.tx_mode is set to TxMode::Normal. if we call process_output one more time in some cases a packet with acks will be sent. this does not look right.

### PR DESCRIPTION
**Pull request by ddragana**
This patch fix a couple of problems with PTO (fixes #308 and #385):
This patch fix a couple of problems with PTO:
- Implement a separate PTO timer for each packet number space,
- Move loss_recovery_state: LossRecoveryState into loss_recovery,
- Keep track of a number of ack_eliciting_outstanding packets,
- If a PTO expires send packets in its pn space and above. For example, if the PTO timer in the Handshake pn space expires we will try to send a datagram with a Handshake packet and a packet in the app pn space if we have keys for app space (this will increase chances that the server can decrypt them and send an ack),
- Fix #385 by adding LossRecoveryState::PtoExpired.

### CODE REVIEW

**Comment by ddragana** [comment]
I need to change something.

File: neqo-transport/src/connection.rs [hunk 1]
```diff
@@ -1173,7 +1191,11 @@ impl Connection {
                         if frame.is_none() {
                             frame = self.send_streams.get_frame(epoch, tx_mode, remaining)
                         }
-                        if frame.is_none() && self.tx_mode == TxMode::Pto {
+
+                        if frame.is_none()
+                            && matches!(self.tx_mode, TxMode::Pto{..})
+                            && self.should_send_ping(epoch)
```
Comment (agrover) [inline neqo-transport/src/connection.rs]: Now that we have a whole method to determine whether to send a ping, suggest moving the matches inside it as well.

File: neqo-transport/src/connection.rs [hunk 2]
```diff
@@ -1275,25 +1300,49 @@ impl Connection {
...
+            // we will limit it on the client side. We will not send a PING if we have received a 1RTT
+            // ack. TODO: fix this when we implement HANDSHAKE_DONE
+            2 => {
+                if self.role == Role::Client {
+                    if let Some(l) = self
+                        .loss_recovery
+                        .largest_acknowledged_pn(PNSpace::ApplicationData)
+                    {
+                        if let Some(f) = self.first_1_rtt_pn {
+                            if l > f {
```
Comment (agrover) [inline neqo-transport/src/connection.rs]: little more verbose on the variable names for l and f?

File: neqo-transport/src/recovery.rs [hunk 3]
```diff
@@ -494,9 +505,18 @@ impl LossRecovery {
...
+                .values()
+                .any(|sp| sp.ack_eliciting),
+            self.spaces[PNSpace::Handshake]
+                .sent_packets
+                .values()
+                .any(|sp| sp.ack_eliciting),
+            self.spaces[PNSpace::ApplicationData]
+                .sent_packets
+                .values()
+                .any(|sp| sp.ack_eliciting)
```
Comment (agrover) [inline neqo-transport/src/recovery.rs]: how about outputting both number of packets AND if any are ack-eliciting in this qinfo?

File: neqo-transport/src/connection.rs [hunk 4]
```diff
@@ -1261,6 +1279,10 @@ impl Connection {
                 SentPacket::new(now, ack_eliciting, tokens, packet.len(), in_flight),
             );
 
+            if self.first_1_rtt_pn.is_none() && epoch == 3 {
+                self.first_1_rtt_pn = Some(hdr.pn);
+            }
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: In the key update changes, packet numbers are already tracked by space.  Maybe you could use that information instead.

File: neqo-transport/src/recovery.rs [hunk 5]
```diff
@@ -543,6 +560,53 @@ impl LossRecovery {
...
+            .min_by_key(|&time| time)
+    }
+
+    pub fn get_min_pto_pn_space(&self, now: Instant) -> Option<PNSpace> {
+        PNSpace::iter()
+            .filter_map(|spc| {
+                if self.spaces[*spc]
+                    .sent_packets
+                    .values()
+                    .any(|sp| sp.ack_eliciting)
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: Can we avoid doing this iteration on every PTO by recording this information on the object when we send a packet?  We could clear it when we process acknowledgments.

Which do you think would be easier to manage?

I you keep it this way around, I would prefer to add a function on LossRecoverySpace that performs this check.  `ack_eliciting_outstanding() -> bool` would help a lot.

File: neqo-transport/src/recovery.rs [hunk 6]
```diff
@@ -543,6 +560,53 @@ impl LossRecovery {
...
+                            None
+                        }
+                    } else {
+                        None
+                    }
+                } else {
+                    None
+                }
+            })
+            .min_by_key(|&spc| spc)
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: This might read better if you factor out the function that produces the iterator, so that these functions only do `min_by_key()` with different keys.

File: neqo-transport/src/recovery.rs [hunk 7]
```diff
@@ -493,10 +504,22 @@ impl LossRecovery {
...
-            self.spaces[PNSpace::ApplicationData].sent_packets.len()
+            self.spaces[PNSpace::Handshake]
+                .sent_packets
+                .values()
+                .any(|sp| sp.ack_eliciting),
+            self.spaces[PNSpace::ApplicationData].sent_packets.len(),
+            self.spaces[PNSpace::ApplicationData]
+                .sent_packets
+                .values()
+                .any(|sp| sp.ack_eliciting)
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: See below about factoring this out into an accessor (or maybe a property).

File: neqo-transport/src/recovery.rs [hunk 8]
```diff
@@ -288,7 +293,8 @@ impl LossRecovery {
     ) {
         qdebug!([self], "packet {:?}-{} sent.", pn_space, packet_number);
         if sent_packet.ack_eliciting {
-            self.time_of_last_sent_ack_eliciting_packet = Some(sent_packet.time_sent);
+            self.spaces[pn_space].time_of_last_sent_ack_eliciting_packet =
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: Rather than accessing the field directly, a setter seems appropriate.  That might help with my suggestion below too.

File: neqo-transport/src/connection.rs [hunk 9]
```diff
@@ -1275,25 +1297,53 @@ impl Connection {
...
             Ok(Some(Datagram::new(path.local, path.remote, out_bytes)))
         }
     }
 
+    fn should_send_ping(&self, epoch: Epoch) -> bool {
+        if !matches!(self.tx_mode, TxMode::Pto{..}) {
+            return false;
+        }
+
+        match epoch {
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: This should match by PNSpace.

File: neqo-transport/src/connection.rs [hunk 10]
```diff
@@ -1275,25 +1297,53 @@ impl Connection {
...
+            // If epoch is initial and we have keys we should send a PING.
+            0 => true,
+            // Currently we do not drop handshake keys, but to avoid sending PINGs for a long time
+            // we will limit it on the client side. We will not send a PING if we have received a 1RTT
+            // ack. TODO: fix this when we implement HANDSHAKE_DONE
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: That's coming; do you want to drop this now?

File: neqo-transport/src/connection.rs [hunk 11]
```diff
@@ -1137,7 +1149,13 @@ impl Connection {
             let mut has_padding = false;
             let cong_avail = match self.tx_mode {
                 TxMode::Normal => usize::try_from(self.loss_recovery.cwnd_avail()).unwrap(),
-                TxMode::Pto => path.mtu(), // send one packet
+                TxMode::Pto { dgram_avail, .. } => {
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: Why are we saving this information on the connection?  Can't the loss recovery spaces hold their PTO state?

Let's say that we send PN 3 in Handshake, can't we ask the loss recovery whether it is time to PTO in that space when it comes time to send a packet in that space?

File: neqo-transport/src/connection.rs [hunk 12]
```diff
@@ -1275,25 +1297,53 @@ impl Connection {
...
             Ok(None)
         } else {
             // Pad Initial packets sent by the client to mtu bytes.
             if self.role == Role::Client && needs_padding {
                 qdebug!([self], "pad Initial to max_datagram_size");
                 out_bytes.resize(path.mtu(), 0);
             }
+            if let TxMode::Pto { dgram_avail, .. } = &mut self.tx_mode {
+                assert!(*dgram_avail > 0);
+                *dgram_avail -= 1;
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: I'm not sure that I understand the use of dgram_avail.  Can you comment this with some explanations.

File: neqo-transport/src/connection.rs (hunk 4 above)
Comment (ddragana) [reply neqo-transport/src/connection.rs]: I will drop this and use HANDSHAKE_DONE and keys discarding. 

I wanted to land this code before we switch version to 25 and turn it on on Nightly (this problem is a blocker because it make use keep connection alive forever). The version switch PR landed so that is late not.... I will update mozilla-central when version 25 is good enough for interoperability (HANDSHAKE_DONE is blocking one)

File: neqo-transport/src/recovery.rs (hunk 5 above)
Comment (ddragana) [reply neqo-transport/src/recovery.rs]: this is call only if PTO timer expires (or if app calls before PTO timer expires and pto time is set - if app is doing it right it should not happe). I do not think wee will do PTO a lot so this function is not a concern, but I think there is one other place that is problematic (in the code that this PR have not touched). I will look into fixing it.

File: neqo-transport/src/connection.rs (hunk 11 above)
Comment (ddragana) [reply neqo-transport/src/connection.rs]: I am not sure either whether we need tx_mode. I think this can be done in a different way.
Also our way of calling 'process' multiple times does not fit nicely with PTO for example. 
dgram_avail is number of packet available to be sent. it should be 1 or 2, but setting it to 2 doesn't work with the way we build frames and packet. I will write a long comment in the e-mail thread you have started.

File: neqo-transport/src/connection.rs (hunk 12 above)
Comment (ddragana) [reply neqo-transport/src/connection.rs]: I will refactor this and remove tx_mode from connection.

File: neqo-transport/src/connection.rs [hunk 13]
```diff
@@ -718,11 +712,10 @@ impl Connection {
     /// Get the time that we next need to be called back, relative to `now`.
     fn next_delay(&mut self, now: Instant) -> Duration {
         qtrace!([self], "Get callback delay");
-        self.loss_recovery_state = self.loss_recovery.get_timer();
-
         let mut delays = SmallVec::<[_; 4]>::new();
+        self.loss_recovery.calculate_timer();
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: Why not return the time from this function?

File: neqo-transport/src/connection.rs [hunk 14]
```diff
@@ -1128,12 +1121,31 @@ impl Connection {
         let mut needs_padding = false;
         let mut close_sent = false;
 
+        // Check whether we are sending packets in PTO mode.
+        let (tx_mode, cong_avail, min_pn_space) =
+            if let Some((min_pn, can_send)) = self.loss_recovery.get_pto_state() {
+                if !can_send {
+                    return Ok(None);
+                }
+                (TxMode::Pto, path.mtu(), min_pn)
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs]: Calling this min_pn is misleading.

File: neqo-transport/src/recovery.rs [hunk 15]
```diff
@@ -356,6 +400,17 @@ impl LossRecovery {
         max(rtt * 9 / 8, GRANULARITY)
     }
 
+    // Calculate PTO duration
+    fn pto_timeout(&self, pn_space: PNSpace) -> Duration {
+        if let Some(d) = self.rtt_vals.pto(pn_space).checked_mul(1 << self.pto_count) {
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]:
```suggestion
        self.rtt_vals.pto(pn_space).checked_mul(1 << self.pto_count).unwrap_or(LOCAL_IDLE_TIMEOUT*2)
```

File: neqo-transport/src/recovery.rs [hunk 16]
```diff
@@ -533,6 +588,96 @@ impl LossRecovery {
...
+            })
+            .min_by_key(|&time| time)
+    }
+
+    pub fn get_min_pto_pn_space(&self, now: Instant) -> Option<PNSpace> {
+        PNSpace::iter()
+            .filter_map(|spc| {
+                if self.spaces[*spc].ack_eliciting_outstanding() {
+                    if let Some(time) = self.spaces[*spc].time_of_last_sent_ack_eliciting_packet {
+                        if time <= (now - self.pto_timeout(*spc)) {
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: I would use `time + self.pto_timeout(*spc) <= now` to avoid weird underflow bugs.  Instant is weird.

File: neqo-transport/src/recovery.rs (hunk 6 above)
Comment (martinthomson) [reply neqo-transport/src/recovery.rs]: I can see the difference now. This is good, but I would prefer a little cleaner factoring.

File: neqo-transport/src/recovery.rs [hunk 17]
```diff
@@ -533,6 +588,96 @@ impl LossRecovery {
...
+            return None;
+        }
+
+        if self.callback_time() > Some(now) {
+            // LR timer, but hasn't expired.
+            return None;
+        }
+
+        // Timer expired and LR was active timer.
+        match &mut self.loss_recovery_state.mode() {
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: You don't need a mutable reference.

File: neqo-transport/src/recovery.rs [hunk 18]
```diff
@@ -533,6 +588,96 @@ impl LossRecovery {
...
+                    None
+                }
+            })
+            .min_by_key(|&spc| spc)
+    }
+
+    pub fn check_loss_detection_timeout(&mut self, now: Instant) -> Option<Vec<SentPacket>> {
+        qdebug!([self], "check_loss_timeouts");
+
+        if matches!(self.loss_recovery_state.mode(), LossRecoveryMode::None) {
```
Comment (martinthomson) [inline neqo-transport/src/recovery.rs]: A simple comparison should work.
