### PR TITLE
Drop packets with unknow versions

### LINKED ISSUE #668: Panic "Attempted to get space from wrong packet type" when running handshakecorruption test
[neqo-client.log](https://github.com/mozilla/neqo/files/4682953/neqo-client.log)

### PR DESCRIPTION
**Pull request by ddragana**
fixes #668

### CODE REVIEW

File: neqo-transport/src/connection.rs [hunk 1]
```diff
@@ -4791,4 +4793,21 @@ mod tests {
         assert_ne!(delay, Duration::from_secs(0));
         assert!(delay > lr_time);
     }
+
+    #[test]
+    fn unknow_version() {
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs:4798]:
```suggestion
    fn unknown_version() {
```

File: neqo-transport/src/connection.rs [hunk 2]
```diff
@@ -4791,4 +4793,21 @@ mod tests {
...
+        let mut client = default_client();
+        // Start the handshake.
+        let _ = client.process(None, now()).dgram();
+
+        const UNKNOW_VERSION_PACKET: &[u8] = &[
```
Comment (martinthomson) [inline neqo-transport/src/connection.rs:4803]:
```suggestion
        const UNKNOWN_VERSION_PACKET: &[u8] = &[
```

This could be smaller.  But it might be better to pad to 1200 so that we hit the full "initial" path.  For that, you might be better using `Vec::resize`
