### PR TITLE
fix: Don't encode large RTT guesses in tickets

### LINKED ISSUE #2088: Huge timeout in `L1` QNS test
We're failing [this `L1` QNS test against the kwik server](https://github.com/mozilla/neqo/actions/runs/10718166512/artifacts/1895573675) due to the test taking longer than 300s.

That seems to be because we are setting **huge timeouts of ~90 seconds** during the connection-close process, and we don't continue on to the next connection in a reasonable time.
```
client  | 93s 96ms DEBUG Setting timeout of 19.971247ms
client  | 93s 96ms DEBUG stream 0 complete
client  | 93s 96ms DEBUG stream BiDi creatable
client  | 93s 96ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 93s 96ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 93s 96ms DEBUG TX blocked, profile=SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 93s 96ms DEBUG [Client 2cc1e081e1fe5325] delay duration 19.923328ms
client  | 93s 96ms DEBUG Setting timeout of 19.923328ms
client  | 93s 96ms DEBUG [Client 2cc1e081e1fe5325] State change from Confirmed -> Closing { error: Application(0), timeout: Instant { tv_sec: 667, tv_nsec: 656536104 } }
client  | 93s 96ms WARN Unhandled event StateChange(Closing { error: Application(0), timeout: Instant { tv_sec: 667, tv_nsec: 656536104 } })
client  | 93s 96ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 93s 96ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 93s 96ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 573, tv_nsec: 125867796 }
client  | 93s 96ms DEBUG [Client 2cc1e081e1fe5325] pn=3 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 42
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 13, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 93s 96ms DEBUG Setting timeout of 94.530598598s
sim     | Forwarding 82 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 48/149 (32.2%)
sim     | Forwarding 1352 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 48/150 (32.0%)
sim     | Forwarding 31 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 48/151 (31.8%)
sim     | Dropping 42 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 49/152 (32.2%)
sim     | Forwarding 24 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 34/135 (25.2%)
client  | 93s146ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 93s146ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 93s146ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 573, tv_nsec: 176033952 }
client  | 93s146ms DEBUG [Client 2cc1e081e1fe5325] pn=4 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 43
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 6283, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 93s147ms DEBUG Setting timeout of 94.48035613s
client  | 93s147ms DEBUG Setting timeout of 94.480342525s
sim     | Forwarding 43 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 49/153 (32.0%)
sim     | Forwarding 29 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 34/136 (25.0%)
client  | 93s178ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 93s178ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 93s178ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 573, tv_nsec: 207809755 }
client  | 93s178ms DEBUG [Client 2cc1e081e1fe5325] pn=5 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 43
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 10255, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 93s178ms DEBUG Setting timeout of 94.448622416s
client  | 93s178ms DEBUG Setting timeout of 94.44861391s
sim     | Dropping 43 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 50/154 (32.5%)
sim     | Forwarding 21 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 34/137 (24.8%)
client  | 108s111ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 108s111ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 108s111ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 588, tv_nsec: 140480140 }
client  | 108s111ms DEBUG [Client 2cc1e081e1fe5325] pn=6 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 45
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 1876839, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 108s111ms DEBUG Setting timeout of 79.515901617s
client  | 108s111ms DEBUG Setting timeout of 79.515885948s
sim     | Dropping 21 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 35/138 (25.4%)
sim     | Dropping 45 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 51/155 (32.9%)
sim     | Forwarding 204 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 35/139 (25.2%)
client  | 108s773ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 108s773ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 108s773ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 588, tv_nsec: 803084953 }
client  | 108s773ms DEBUG [Client 2cc1e081e1fe5325] pn=7 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 45
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 1959665, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 108s774ms DEBUG Setting timeout of 78.853327351s
client  | 108s774ms DEBUG Setting timeout of 78.853304208s
sim     | Forwarding 204 bytes 193.167.100.100:443 -> 193.167.0.100:42465, dropped 35/140 (25.0%)
client  | 108s774ms DEBUG [Client 2cc1e081e1fe5325] output_path send_profile SendProfile { limit: 1152, pto: None, probe: (), paced: false }
client  | 108s774ms DEBUG Building Short dcid Some(CID [8]: f734cc7d2e99a52a)
client  | 108s774ms DEBUG [Recvd-ap] immediate_ack at Instant { tv_sec: 588, tv_nsec: 804030443 }
client  | 108s774ms DEBUG [Client 2cc1e081e1fe5325] pn=8 type=Short pri-path:f734cc7d2e99a52a 0.0.0.0:42465->193.167.100.100:443 IpTos(Cs0, NotEct) len 45
client  |   TX -> Ack { largest_acknowledged: 2, ack_delay: 1959783, first_ack_range: 2, ack_ranges: [], ecn_count: None }
client  |   TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: "kthxbye!" }
client  | 108s774ms DEBUG Setting timeout of 78.852422597s
client  | 108s774ms DEBUG Setting timeout of 78.852411897s
sim     | Forwarding 45 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 51/156 (32.7%)
sim     | Forwarding 45 bytes 193.167.0.100:42465 -> 193.167.100.100:443, dropped 51/157 (32.5%)
server  | QLog: done with 9840ca8b42f950a3.qlog
server  | QLog: done with d58f290ebd9bcfa9d5.qlog
server  | QLog: done with 2cc1e081e1fe5325.qlog
client  | 187s628ms DEBUG [Client 2cc1e081e1fe5325] State change from Closing { error: Application(0), timeout: Instant { tv_sec: 667, tv_nsec: 656536104 } } -> Closed(Application(0))
client  | 187s628ms INFO Closing timer expired
client  | 187s628ms DEBUG Output::None
client  | 187s628ms WARN Unhandled event StateChange(Closed(Application(0)))
client  | 187s628ms DEBUG Timer fired while closed
client  | 187s628ms DEBUG Output::None
```

### PR DESCRIPTION
**Pull request by larseggert**
Because under lossy conditions (e.g., QNS `handshakeloss` test), the guess can be multiple times the actual RTT, which when encoded in the resumption ticket will cause an extremely slow second handshake, often causing the test to time out.

Broken out of #1998
Fixes #2088

### CODE REVIEW

**Comment by larseggert** [comment]
This needs more work. I thought the code here
https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/path.rs#L971-L990
was an optimization, but the `idle_timeout_crazy_rtt` test hangs when I remove it.

@martinthomson do you remember why this was put in? This kind of RTT guessing isn't using packet number and so becomes very wrong very quickly when there is loss.

File: neqo-transport/src/connection/mod.rs [hunk 1]
```diff
@@ -594,9 +594,25 @@ impl Connection {
     fn make_resumption_token(&mut self) -> ResumptionToken {
         debug_assert_eq!(self.role, Role::Client);
         debug_assert!(self.crypto.has_resumption_token());
+        // Values less than GRANULARITY are ignored when using the token, so use 0 where needed.
```
Comment (mxinden) [inline neqo-transport/src/connection/mod.rs:597]: Do I understand correctly, that you are referring to `RttEstimate::set_initial` here?

https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/rtt.rs#L64-L70

File: neqo-transport/src/connection/mod.rs [hunk 2]
```diff
@@ -594,9 +594,25 @@ impl Connection {
...
         let rtt = self.paths.primary().map_or_else(
-            || RttEstimate::default().estimate(),
-            |p| p.borrow().rtt().estimate(),
+            // If we don't have a path, we don't have an RTT.
+            || Duration::from_millis(0),
+            |p| {
+                let rtt = p.borrow().rtt().estimate();
+                if self.stats.borrow().frame_rx.ack == 0 {
```
Comment (mxinden) [inline neqo-transport/src/connection/mod.rs:603]: I consider `stats` a purely auxiliary mechanism, used for telemetry only. Is that consideration wrong?

If not, I wouldn't consider depending on `stats` here clean.

How about using `RttEstimate::first_sample_time` instead?

https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/rtt.rs#L34

E.g. something along the lines of:

```suggestion
                if p.borrow().rtt().first_sample_time().is_none() {
```

File: neqo-transport/src/connection/mod.rs (hunk 1 above)
Comment (larseggert) [reply neqo-transport/src/connection/mod.rs:597]: Yes.

File: neqo-transport/src/connection/mod.rs (hunk 2 above)
Comment (larseggert) [reply neqo-transport/src/connection/mod.rs:603]: Because we set `first_sample_time` to something even if that something is just an RTT guess and not a measured RTT. (I used that first, thinking exactly the same, but it doesn't work.)

Comment (mxinden) [reply neqo-transport/src/connection/mod.rs:603]: `RttEstimate::update` takes a `bool` `confirmed`:

https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/rtt.rs#L86-L93

`RttEstimate::update` is called by two functions:

- https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/recovery/mod.rs#L559-L565
- https://github.com/mozilla/neqo/blob/75372c214c5a5d1d220e5cc502afffad8d820e21/neqo-transport/src/path.rs#L970

How about replacing `confirmed with additional state:

``` rust
struct RttEstimate {
  // ....
  best_source: Source,
}

pub enum Source {
  Estimate,
  Ack,
  /// Ack on a confirmed connection.
  AckConfirmed,
}

impl RttEstimate {
    pub fn update(
        &mut self,
        qlog: &NeqoQlog,
        mut rtt_sample: Duration,
        ack_delay: Duration,
        // Provide the root source of the update.
        source: Source,
        now: Instant,
    ) {

```

`rtt_sample` could then call `RttEstimate::update` with `Source::Ack` or `Source::AckConfirmed`. `discard_packet` would pass `Source::Estimate`.

`RttEstimate` can then expose `best_source` to e.g. `Connection` above, or expose `RttEstimate::estimate` and `RttEstimate::guesstimate` based on `Source`.

What do you think?

File: neqo-transport/src/rtt.rs [hunk 3]
```diff
@@ -83,17 +96,24 @@ impl RttEstimate {
...
     pub fn update(
         &mut self,
         qlog: &NeqoQlog,
         mut rtt_sample: Duration,
         ack_delay: Duration,
-        confirmed: bool,
+        source: RttSource,
         now: Instant,
     ) {
+        debug_assert!(source >= self.best_source);
```
Comment (mxinden) [inline neqo-transport/src/rtt.rs:111]: Neat!

**Review by mxinden — APPROVED** [review]
Thank you for the elaborate test!
