### PR TITLE
More complete testing of RxStreamOrderer

### LINKED ISSUE #866: Loss of received bytes when overlapping at the end
If we receive new bytes that overlap the end of existing bytes, we were dropping some of those existing bytes if the length of the newly received bytes was less than the existing bytes.  Worse, we could have crashed if the truly new bytes were shorter than the overlap.

### PR DESCRIPTION
**Pull request by martinthomson**
I discovered a bug in testing that was hard to reproduce otherwise.

The existing tests that would have caught this used a buffer of the same
length as the one that it overlapped with, hiding the error.

Rather than try to fix just that test case, I added a bunch of new
tests.  This probably overdoes it by quite a bit, but I would rather
have that than miss an error.

Closes #866.

### CODE REVIEW

File: neqo-transport/src/recv_stream.rs [hunk 1]
```diff
@@ -556,6 +556,131 @@ impl RecvStream {
...
+
+    /// An overlap with no new bytes.
+    #[test]
+    fn recv_overlap_duplicate() {
+        recv_ranges(&[10..20, 11..12, 0..10], 20);
+        recv_ranges(&[10..20, 10..15, 0..10], 20);
+        recv_ranges(&[10..20, 14..20, 0..10], 20);
+        // Now with the first range split.
+        recv_ranges(&[10..14, 14..20, 10..15, 0..10], 20);
+    }
```
Comment (ddragana) [inline neqo-transport/src/recv_stream.rs:683]: Let overdo it a bit more:
can you add a test that overlaps 3 ranges:
10..15, 16..20, 21..25, 10..25 ?

Comment (martinthomson) [reply neqo-transport/src/recv_stream.rs:683]: Happy to overdo things more :)
