### PR TITLE
fix: Disable some `hrtime` tests on `aarch64`

### LINKED ISSUE #2422: `hrtime::test::update_multi` fails occasionally in CI on Ubuntu
Debug and fix or disable.

### PR DESCRIPTION
**Pull request by larseggert**
Resolves #2422

### CODE REVIEW

File: neqo-common/src/hrtime.rs [hunk 1]
```diff
@@ -487,6 +492,7 @@ mod test {
         thr.join().unwrap();
     }
 
+    #[cfg(not(target_arch = "aarch64"))] // This test is flaky on linux/arm.
```
Comment (mxinden) [inline neqo-common/src/hrtime.rs:495]: I only recall `update_multi` to be flaky. If that is really the case, I would prefer only disabling `update_multi` on `aarch64`.

**Review by mxinden — APPROVED** [review]

File: neqo-common/src/hrtime.rs (hunk 1 above)
Comment (larseggert) [reply neqo-common/src/hrtime.rs:495]: It's other ones, too. Check the various links to failures at #2422.
