### PR TITLE
Do not post multiple unnecessary  DataReadable events

### LINKED ISSUE #973: We have too many DataReadable events
I was looking at some Firefox logs and we have too many DataReadable events. They are received even after a stream has been closed.

I seen this on blog.cloudflare.com, but Io have only necko logging. I will try to reproduce it with neqo logging. should not be hard.

### PR DESCRIPTION
**Pull request by ddragana**
Fixes #973

### CODE REVIEW

**Comment by ddragana** [comment]
There is some code in necko that is executed on each of this events and it is really not needed.

This is bothers me because Firefox is producing to much logging for so many unnecessary events.

File: neqo-transport/src/connection/tests/stream.rs [hunk 1]
```diff
@@ -503,3 +503,59 @@ fn max_streams_after_bidi_closed() {
...
+    let stream_id = client.stream_create(StreamType::BiDi).unwrap();
+    client.stream_send(stream_id, &[0x00]).unwrap();
+    let out = client.process(None, now());
+    let _ = server.process(out.dgram(), now());
+
+    // We have a data_readable event.
+    let stream_readable = |e| matches!(e, ConnectionEvent::RecvStreamReadable {..});
+    assert!(server.events().any(stream_readable));
+
+    // Send one more datta frame from client. The previous stream data has not been read yet,
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/stream.rs:523]:
```suggestion
    // Send one more data frame from client. The previous stream data has not been read yet,
```

File: neqo-transport/src/connection/tests/stream.rs [hunk 2]
```diff
@@ -503,3 +503,59 @@ fn max_streams_after_bidi_closed() {
...
+    // therefore there should not be a new DataReadable event.
+    client.stream_send(stream_id, &[0x00]).unwrap();
+    let out_second_data_frame = client.process(None, now());
+    let _ = server.process(out_second_data_frame.dgram(), now());
+    assert!(!server.events().any(stream_readable));
+
+    // One more frame with a fin will not produce a new DataReadable event, becasue the
```
Comment (martinthomson) [inline neqo-transport/src/connection/tests/stream.rs:530]:
```suggestion
    // One more frame with a fin will not produce a new DataReadable event, because the
```

**Review by martinthomson — COMMENTED** [review]
Approved.  Thanks for fixing this.

I only found a couple of typos.
